x-common-general: &common-general
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 512M

services:
  sate:
    <<: *common-general
    image: ghcr.io/stegripe/discord-sendiri-bot:latest-dev
    container_name: discord-sendiri-bot
    env_file: .env
    networks:
      - net

networks:
  net:
