name: Lint code and compile setup script

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    uses: stegripe/workflows/.github/workflows/pnpm-lint-and-test.yaml@bcba2efce1d596253f17e161f75174079695b545 # main
    secrets: inherit
